### ISSUE TITLE
Make urlPrefix path of the WebJarBundle and WebJarServlet configurable

### ISSUE THREAD

**Issue by zapodot** [bazaarvoice/dropwizard-webjars-bundle#6]
In the current version the URI_PREFIX is a hard-coded constant defined in WebJarServlet. In my current project the URL prefix "/webjars/" is not sufficient. There really should be a way to specifiy it.

I will propose the change through a pull request ASAP

**Comment by uded** [comment]
+1

It's not a big deal, but it would make sense to use something like "assets" for the prefix...
